//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notes_MarketPlace.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberDetailsData
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<int> TotalNotesUnderReview { get; set; }
        public Nullable<int> TotalPublishedNotes { get; set; }
        public Nullable<int> TotalDownloadedNotes { get; set; }
        public Nullable<decimal> TotalExpense { get; set; }
        public Nullable<decimal> TotalEarning { get; set; }
    }
}
