//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notes_MarketPlace.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumberofDownloads
    {
        public int Id { get; set; }
        public Nullable<int> NoteID { get; set; }
        public Nullable<int> Downloads { get; set; }
    }
}
